#!/usr/bin/env bash

case $BLOCK_BUTTON in
  4) xbacklight +1 ;; # scroll up, increase
  5) xbacklight -1 ;; # scroll down, decrease
esac


INTBRIGHT=$(echo "($(xbacklight)+0.5)/1" | bc)
echo  $INTBRIGHT%
